# mkdocs.yml - Configuration for MkDocs

site_name: Go Performance Patterns
repo_url: https://github.com/astavonin/go-performance-book
site_url: https://astavonin.github.io/go-performance-book/

theme:
  name: material
  palette:
    scheme: default
  icon:
    annotation: material/alert-circle
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Common Go Patterns for Performance:
    - Common Go Patterns for Performance: 01-common-patterns/index.md
    - Object Pooling: 01-common-patterns/object-pooling.md
    - Memory Preallocation: 01-common-patterns/mem-prealloc.md
    - Efficient Buffering: 01-common-patterns/buffered-io.md
    - Goroutine Worker Pools: 01-common-patterns/worker-pool.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.details

plugins:
  - search
  - git-revision-date-localized
  - include-markdown
